@startuml
skinparam classAttributeIconSize 0
skinparam classBackgroundColor LOGIC_COLOR

class FilterDateCommand {
    - startDate : LocalDate
    - endDate : LocalDate
    - sortOrder : String

    - sortFilterDate() : Comparator<Person>
    + execute(model : Model) : CommandResult
}

class FilterDateCommandParser {
    - MAX_YEARS_RANGE : int = 5

    + parse(args : String) : FilterDateCommand
}

interface Parser {
    + parse(userInput : String) : T
}

abstract class Command {
    + execute(model : Model) : CommandResult
}

interface Model {
    + getRenewalsList() : ObservableList<Person>
    + updateRenewalsList(predicate : Predicate<Person>) : void
    + updateSortedRenewalsList(comparator : Comparator<Person>) : void
}

class MainWindow {
    - filterLabel : Label

    - updateFilterLabelEmpty() : void
    + updateFilterLabel(startDate : LocalDate, endDate : LocalDate) : void
}

FilterDateCommandParser -up-|> Parser
FilterDateCommand -up-|> Command
FilterDateCommandParser ..> FilterDateCommand
FilterDateCommand ..> Model
MainWindow -up-|> UiPart
@enduml
