@startuml
skinparam classAttributeIconSize 0
skinparam classBackgroundColor LOGIC_COLOR
skinparam ArrowColor BLACK
skinparam ClassBorderColor BLACK

class RenewCommand {
    - policyNumber : String
    - newRenewalDate : RenewalDate
    + execute(model : Model) : CommandResult
}

class RenewCommandParser {
    + parse(args : String) : RenewCommand
}

interface Parser<T> {
    + {abstract} parse(userInput : String) : T
}

interface Model {
    + updatePerson(target : Person, editedPerson : Person)
    + getFilteredPersonList() : ObservableList<Person>
}

RenewCommandParser ..|> Parser
RenewCommandParser ..> RenewCommand : creates >
RenewCommand --> Model : uses >
@enduml
