@startuml
!include style.puml
skinparam dpi 300
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR
skinparam classBackgroundColor LOGIC_COLOR
skinparam nodesep 40
skinparam ranksep 40
scale 0.6

Class "<<interface>>\nParser" as Parser {
    + {abstract} parse(userInput : String) : T
}

Class "<<interface>>\nModel" as Model {
    + updatePerson(target : Person, editedPerson : Person)
    + getFilteredPersonList() : ObservableList<Person>
}

Class RenewCommand {
    - policyNumber : String
    - newRenewalDate : RenewalDate
    + execute(model : Model) : CommandResult
}

Class RenewCommandParser {
    + parse(args : String) : RenewCommand
}

RenewCommandParser ..|> Parser
RenewCommandParser ..> RenewCommand
RenewCommand ..> Model
@enduml
