@startuml
!include style.puml

skinparam defaultFontSize 24

box Logic LOGIC_COLOR_T1
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":ViewRenewalsCommandParser" as ViewRenewalsCommandParser LOGIC_COLOR
participant "command:ViewRenewalsCommand" as ViewRenewalsCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> AddressBookParser : parseCommand()
activate AddressBookParser

AddressBookParser -> ViewRenewalsCommandParser : parse()
activate ViewRenewalsCommandParser

create ViewRenewalsCommand
ViewRenewalsCommandParser -> ViewRenewalsCommand : new()
activate ViewRenewalsCommand

ViewRenewalsCommand --> ViewRenewalsCommandParser
deactivate ViewRenewalsCommand

ViewRenewalsCommandParser --> AddressBookParser : command
deactivate ViewRenewalsCommandParser

[<-- AddressBookParser : command
deactivate AddressBookParser

[-> ViewRenewalsCommand : execute()
activate ViewRenewalsCommand

ViewRenewalsCommand -> Model : updateFilteredPersonList()
activate Model

Model --> ViewRenewalsCommand
deactivate Model

[<-- ViewRenewalsCommand : result
deactivate ViewRenewalsCommand

@enduml
