@startuml
!include style.puml

skinparam defaultFontSize 16
skinparam ParticipantFontColor white
skinparam ArrowColor black

box Logic LOGIC_COLOR_T1
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":ViewRenewalsCommandParser" as Parser LOGIC_COLOR
participant ":ViewRenewalsCommand" as Command LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> AddressBookParser : parse("viewrenewals n/30 s/date")
activate AddressBookParser

AddressBookParser -> Parser : parse(" n/30 s/date")
activate Parser

create Command
Parser -> Command : new(30, "date")
activate Command

Command --> Parser
deactivate Command

Parser --> AddressBookParser : cmd
deactivate Parser

[<-- AddressBookParser : cmd
deactivate AddressBookParser

[-> Command : execute(model)
activate Command

Command -> Model : updateRenewals(predicate)
activate Model
Model --> Command
deactivate Model

Command -> Model : sortRenewals(comparator)
activate Model
Model --> Command
deactivate Model

Command -> Model : getRenewals()
activate Model
Model --> Command : list
deactivate Model

[<-- Command : result
deactivate Command

@enduml
